### ISSUE TITLE
Storage implementation example

### ISSUE THREAD

**Issue by emcniece** [ceph/ceph-csi-operator#231]
Hello, I am seeking some clarification on how ceph-csi-operator should be used after installation. I may be misunderstanding this repo.

I have installed resources as per https://github.com/ceph/ceph-csi-operator/blob/main/docs/quick-start.md - what is the next step to using Ceph for volume storage? Can it be used as a storage class, eg.

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-test
  namespace: ceph-csi-test
spec:

  storageClassName: ceph-csi-operator   # Is there a classname we can use here?

  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 1Gi
```

Thank you in advance for your advice.
