### ISSUE TITLE
 CephCSIConfig  CRD should also have subvolume group pinning

### ISSUE THREAD

**Issue by parth-gr** [ceph/ceph-csi-operator#46]
# Describe the feature you'd like to have #
CephCSIConfig  CRD should also have subvolume group pinning
```
cephFS:
    subvolumeGroup: csi
    kernelMountOptions: readdir_max_bytes=1048576,norbytes
    fuseMountOptions: debug
    pinning:
       type: value
```       
Similar to rook https://github.com/rook/rook/blob/c8f9e6549d457ec202ed6bb5000afb2930d2052a/Documentation/CRDs/Shared-Filesystem/ceph-fs-subvolumegroup-crd.md?plain=1#L31
