### ISSUE TITLE
have driver specific section in CephCSIDriver CRD for configurations

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi-operator#6]
am still not fine with one , we need to bring this under cephfs or filesystem section but for now, lets get this merged and bring that as a new Issue later on.

_Originally posted by @Madhu-1 in https://github.com/ceph/ceph-csi-operator/pull/1#discussion_r1616822737_

**Comment by Madhu-1** [comment]
```yaml
cephFsKernelClient: true
cephFsKernelMountOptions: ms_mode=secure
```

should be 

```yaml
cephfs:
  kernelClient: true
  kernelMountOptions: ms_mode=secure
```
