### ISSUE TITLE
New field in the operatorConfig CRD for the deployment model.

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi-operator#7]
IMO, the deployment mode (the operator's 'watch' scope) control makes the most sense here

something like...
```yaml
spec:
  watchNamespaces: # if empty, only watch current ns, ['*'] means watch all
    - ns1
    - ns2
    - etc
```

_Originally posted by @BlaineEXE in https://github.com/ceph/ceph-csi-operator/pull/1#discussion_r1617728803_
